apiVersion: v1
kind: Service
metadata:
  name: svc-sm-bank-transaction
spec:
  selector:
    app: sm-bank-transaction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
